# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["model.py"]

doc_url = "https://Eija1 #City-of-Helsinki.github.io/ml_project_template_test_Eija/"

git_url = "https://github.com/Eija1 #City-of-Helsinki/ml_project_template_test_Eija/tree/master/"

def custom_doc_links(name): return None
